name: Publish Unity Package

on: 
  workflow_dispatch:
  push: 
      branches: 
        - main
    
jobs:
  Use:
      uses: etn218n/shared-npm-workflow/.github/workflows/publish.yml@main
      secrets: inherit